### ISSUE TITLE
Service Account api to enable

### ISSUE THREAD

**Issue by billyandco** [methodpark/dart-publisher#5]
Hello team !
Thank you very much for doing this project

Can you add in README file what to enable to upload apk or appbundles
like Google Play Android Developer API or stuff like that

Thank you

**Comment by traveling-developer** [comment]
This is already mentioned in the README.
"For using the Google Play features a Google Cloud service account with the correct permissions is needed. Have a look at the Google [documentation](https://cloud.google.com/docs/authentication/getting-started#cloud-console) for more information."
There everything is documented. Does it help?
